spring:
  application:
    name: User-Partner
  datasource:
    url: jdbc:mysql://localhost:3306/partners?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    Session失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: localhost
    port: 6379
    database: 0


# MyBatis 映射配置
mybatis-plus:

  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhangchuang.usercenter.model.domain.User
  configuration:
    map-underscore-to-camel-case: true
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto
# 应用服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

